package com.csye6225.fall2018.courseservice.datamodels;

import java.util.Set;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "course")
public class Course
{
    private String id;
    private String courseId;
    private String professorId;
    private String taId;
    private String department;
    private String boardId;
    private Set<String> roster;

    public Course()
    {

    }

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId()
    {
        return id;
    }

    public void setId(String id)
    {
        this.id = id;
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "courseId", attributeName = "courseId")
    public String getCourseId()
    {
        return courseId;
    }

    public void setCourseId(String courseId)
    {
        this.courseId = courseId;
    }

    @DynamoDBAttribute(attributeName = "professorId")
    public String getProfessorId()
    {
        return professorId;
    }

    public void setProfessorId(String professorId)
    {
        this.professorId = professorId;
    }

    @DynamoDBAttribute(attributeName = "taId")
    public String getTaId()
    {
        return taId;
    }

    public void setTaId(String taId)
    {
        this.taId = taId;
    }

    @DynamoDBAttribute(attributeName = "department")
    public String getDepartment()
    {
        return department;
    }

    public void setDepartment(String department)
    {
        this.department = department;
    }

    @DynamoDBAttribute(attributeName = "boardId")
    public String getBoardId()
    {
        return boardId;
    }

    public void setBoardId(String boardId)
    {
        this.boardId = boardId;
    }

    @DynamoDBAttribute(attributeName = "roster")
    public Set<String> getRoster()
    {
        return roster;
    }

    public void setRoster(Set<String> roster)
    {
        this.roster = roster;
    }

}
